<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_gwt-Image</name>
   <tag></tag>
   <elementGuidId>462df363-976c-46cd-8532-b39a9faec36b</elementGuidId>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tfgld4510m000-0-button-std-edit.find&quot;)/img[@class=&quot;gwt-Image&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABbElEQVQ4T5XSTStFQRzH8XtDFixsSB7vwkNWSiQLC08lC3kDNxvKQ0phobwAedgikhLegEQSRexuXYWEQhaeyorCAt/faabG6d4Opz7NnJlzfvOfMycc+n2VcjuIVkTwhjhWsYRP3/OhsDMwRH8cqbjHJTJRiRQT1EF764bYgGEGJ3GDfmzhyzyYQzuGAVyjFs82RAFlOMEd6vDkL9Pcj9BOYBmdbsA8N91ow2aSl+3wkakgn/ZBg6rgCukowndAQBfzC4hixQZ80DlAc8DLmm7ALkahD+5V8IpzVP8hQNvcgD76tA04pFODXLwEhEwxr+NuMpV4FfRg1iQqOdlVwMQpdErl8I5ZAWnQ31aBPswlSMhjbB1V0A9Wj0cboLYEe9Aq+1jEBTKgcnuR5QSf0W9UiPsra5UZtJvK3EK02juK/SFugJ2L0GlBIXTE2t4Osk2VqtZesUQB7sr+vraordqQtf8GKFAh2zhG9Ac2W0adq+wu6gAAAABJRU5ErkJggg==</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gwt-Image</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tfgld4510m000-0-button-std-edit.find</value>
   </webElementProperties>
</WebElementEntity>
