<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_I tegration Transactions</name>
   <tag></tag>
   <elementGuidId>d02577eb-6e17-40fe-86bb-ec5a53a6a0f3</elementGuidId>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;appnav-item-mtfext000-menu-mtfextint000-Integration-with-Other-Modules-mtfextint002-Integration-Inquiries-&amp;-Reports-tfgld4510m000-label&quot;)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>appnav-item-mtfext000-menu-mtfextint000-Integration-with-Other-Modules-mtfextint002-Integration-Inquiries-&amp;-Reports-tfgld4510m000-label</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>I tegration Transactions by Project/Order</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Label</value>
   </webElementProperties>
</WebElementEntity>
