<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_tfgld4510m000-7-grid-1-tfg</name>
   <tag></tag>
   <elementGuidId>8ccfab4e-bc61-48d4-8db2-cf6a8fc1fa36</elementGuidId>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tfgld4510m000-7-grid-1-tfgld418.fitr-8-filter-value-control-trigger-button-image&quot;)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAGCAYAAAD+Bd/7AAAAlElEQVQYV2M0NTXt+PPnTwYTExMfAwMDIxAz/P///x+QesHIyNjHaGVlJfbjx49aoGAUUJEgkP4LlDwPpPuA/LUgHUz6+vqazMzM5UB2IFDXPSBuAirYfvbs2W9gIx0cHFg+fvyoDVSU9e/fv8OsrKybTp48+RlkG1gBFDAbGxsLsrGxfT1+/PgPkCTITcgKkNQimAAe1TeyO1tOfwAAAABJRU5ErkJggg==</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tfgld4510m000-7-grid-1-tfgld418.fitr-8-filter-value-control-trigger-button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gwt-Image</value>
   </webElementProperties>
</WebElementEntity>
